### PR TITLE
Delete BannerPlaceAction

### PR DESCRIPTION
**Pull request by Gymnasiast**
Required by https://github.com/OpenRCT2/OpenRCT2/pull/10674

### CODE REVIEW

**Comment by tupaschoal** [comment]
Is it completely broken?

**Comment by duncanspumpkin** [comment]
@tupaschoal it will need to be recreated after that pr is merged. It's broken because the size of the parameters have been changed.

**Comment by tupaschoal** [comment]
Thanks for letting me know

**Review by ZehMatt — APPROVED** [review]
No objections, would be nice to get a replacement back tho :)

**Pull request merged**
